# Alacritty Configuration
# JetBrains Mono Nerd Font with Semi-Transparent Background

# Font configuration
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0

# Window configuration
[window]
opacity = 0.85  # Semi-transparent background (0.0 = fully transparent, 1.0 = opaque)
padding = { x = 8, y = 8 }
decorations = "full"  # Keep window decorations for title bar and window controls
startup_mode = "Windowed"
dynamic_title = true
dynamic_padding = false

# Colors (using a modern dark theme)
[colors.primary]
background = "#1e1e2e"  # Dark background
foreground = "#cdd6f4"  # Light foreground
dim_foreground = "#6c7086"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#f9e2af"

# footer_bar removed - not supported in current version

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

# Normal colors
[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

# Bright colors
[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

# Dim colors
[colors.dim]
black = "#313244"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#6c7086"

# Cursor configuration
[cursor]
style = "Block"
unfocused_hollow = true
thickness = 0.15

# Mouse configuration
[mouse]
hide_when_typing = false

# Selection configuration
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

# Bell configuration
[bell]
animation = "EaseOutExpo"
duration = 0
color = "#f9e2af"

# Terminal configuration
[terminal]
shell = { program = "/bin/bash", args = ["--login"] }

# Working directory not supported in current version

# Scrolling configuration
[scrolling]
history = 10000
multiplier = 3